using System;
using System.Collections.Generic;
using System.Linq;

namespace Polaris.Pevt.Diagnostics
{
    /// <summary>
    /// PEVTxxxx 全部诊断编号的唯一集中目录，逐条对应 PEVT-静态诊断表.md。
    /// 新增诊断只应追加到对应编号分区末尾；已分配编号不得改变含义，删除后不得复用。
    /// </summary>
    public static class DiagnosticCatalog
    {
        private static readonly DiagnosticDescriptor[] Entries =
        {
            new DiagnosticDescriptor("PEVT1001", "UnexpectedToken", DiagnosticSeverity.Error, "出现当前语法不能识别的字符或 token。"),
            new DiagnosticDescriptor("PEVT1002", "UnterminatedString", DiagnosticSeverity.Error, "双引号字符串到行末或文件末尾仍未闭合。"),
            new DiagnosticDescriptor("PEVT1003", "EventBlockNotSupported", DiagnosticSeverity.Error, "出现 `{` 或 `}`；当前语法不支持事件块。"),
            new DiagnosticDescriptor("PEVT1004", "UnterminatedCharacter", DiagnosticSeverity.Error, "单引号字符到行末或文件末尾仍未闭合。"),
            new DiagnosticDescriptor("PEVT1005", "MultipleStatementsOnLine", DiagnosticSeverity.Error, "除 `$raw` 原始文本块和合法多行字符串外，同一物理行中出现多条普通语句。"),
            new DiagnosticDescriptor("PEVT1006", "UnexpectedLineBreak", DiagnosticSeverity.Error, "普通表达式、参数列表、定义签名或流程控制行在完成前发生不属于合法多行字符串的换行。"),
            new DiagnosticDescriptor("PEVT1007", "SemicolonStatementTerminator", DiagnosticSeverity.Error, "使用分号结束或分隔 PEVT 普通语句。"),
            new DiagnosticDescriptor("PEVT1008", "InvalidIdentifier", DiagnosticSeverity.Error, "标识符或调用名称不符合规定的 ASCII 字母、数字和下划线格式。"),
            new DiagnosticDescriptor("PEVT1009", "InvalidSourceEncoding", DiagnosticSeverity.Error, "源文件不是合法 UTF-8，或 BOM 出现在文件起始位置以外。"),
            new DiagnosticDescriptor("PEVT1010", "UnterminatedBlockComment", DiagnosticSeverity.Error, "`/*` 块注释到文件末尾仍未遇到结束分隔符 `*/`。"),
            new DiagnosticDescriptor("PEVT1011", "MisalignedMultilineString", DiagnosticSeverity.Error, "多行字符串某个续接段的开始双引号没有与第一段字符串的开始双引号位于同一源文件列。"),
            new DiagnosticDescriptor("PEVT1012", "InvalidMultilineStringContinuation", DiagnosticSeverity.Error, "字符串行末 `+` 后的下一物理行不是直接续接的字符串字面量，续接缩进使用了制表符，或各段之间插入了空行或注释。"),
            new DiagnosticDescriptor("PEVT1013", "UnterminatedMultilineStringContinuation", DiagnosticSeverity.Error, "字符串以行末 `+` 请求继续，但在文件末尾前没有出现所需的下一段字符串字面量。"),
            new DiagnosticDescriptor("PEVT1101", "MissingEventId", DiagnosticSeverity.Error, "文件没有 `id` 声明。"),
            new DiagnosticDescriptor("PEVT1102", "EventIdNotFirst", DiagnosticSeverity.Error, "`id` 不是文件的第一个语法语句。"),
            new DiagnosticDescriptor("PEVT1103", "DuplicateEventId", DiagnosticSeverity.Error, "同一文件出现多个 `id` 声明。"),
            new DiagnosticDescriptor("PEVT1104", "MissingEventIdValue", DiagnosticSeverity.Error, "`id` 后没有事件 ID。"),
            new DiagnosticDescriptor("PEVT1105", "EventIdMustBeString", DiagnosticSeverity.Error, "`id` 后的事件 ID 不是双引号字符串。"),
            new DiagnosticDescriptor("PEVT1106", "UnexpectedEventIdArgument", DiagnosticSeverity.Error, "事件 ID 字符串后还有额外参数。"),
            new DiagnosticDescriptor("PEVT1107", "InvalidEnablePlacement", DiagnosticSeverity.Error, "`enable` 能力声明没有位于紧跟 `id` 的连续能力声明区域中。"),
            new DiagnosticDescriptor("PEVT1108", "DuplicateEnableDeclaration", DiagnosticSeverity.Error, "同一文件重复声明相同的 `cs` 或 `async` 能力。"),
            new DiagnosticDescriptor("PEVT1109", "InvalidEnabledCapability", DiagnosticSeverity.Error, "`enable` 后不是精确的 `cs` 或 `async`，或能力名称后还有额外参数。"),
            new DiagnosticDescriptor("PEVT1110", "EmptyEventId", DiagnosticSeverity.Error, "事件 ID 双引号内没有任何字符。"),
            new DiagnosticDescriptor("PEVT1111", "InvalidEventIdCharacter", DiagnosticSeverity.Error, "事件 ID 包含 ASCII 字母、数字和 Unicode 中文汉字以外的字符。"),
            new DiagnosticDescriptor("PEVT1201", "UnknownStatement", DiagnosticSeverity.Error, "行首内容不属于任何已定义的事件语句。"),

            new DiagnosticDescriptor("PEVT2001", "MissingIfExpression", DiagnosticSeverity.Error, "`if` 后没有表达式。"),
            new DiagnosticDescriptor("PEVT2002", "MissingEndIf", DiagnosticSeverity.Error, "`if` 没有对应的 `endif`。"),
            new DiagnosticDescriptor("PEVT2003", "OrphanElif", DiagnosticSeverity.Error, "`elif` 不属于任何尚未闭合的 `if`。"),
            new DiagnosticDescriptor("PEVT2004", "MissingElifExpression", DiagnosticSeverity.Error, "`elif` 后没有表达式。"),
            new DiagnosticDescriptor("PEVT2005", "ElifAfterElse", DiagnosticSeverity.Error, "同一个 `if` 中的 `elif` 出现在 `else` 之后。"),
            new DiagnosticDescriptor("PEVT2006", "OrphanElse", DiagnosticSeverity.Error, "`else` 不属于任何尚未闭合的 `if`。"),
            new DiagnosticDescriptor("PEVT2007", "DuplicateElse", DiagnosticSeverity.Error, "同一个 `if` 中出现多个 `else`。"),
            new DiagnosticDescriptor("PEVT2008", "ElseHasExpression", DiagnosticSeverity.Error, "`else` 后出现表达式或其他参数。"),
            new DiagnosticDescriptor("PEVT2009", "OrphanEndIf", DiagnosticSeverity.Error, "`endif` 没有对应的 `if`。"),
            new DiagnosticDescriptor("PEVT2010", "EndIfHasArguments", DiagnosticSeverity.Error, "`endif` 后出现参数。"),

            new DiagnosticDescriptor("PEVT2101", "MissingWhileExpression", DiagnosticSeverity.Error, "`while` 后没有表达式。"),
            new DiagnosticDescriptor("PEVT2102", "MissingEndWhile", DiagnosticSeverity.Error, "`while` 没有对应的 `endwhile`。"),
            new DiagnosticDescriptor("PEVT2103", "OrphanEndWhile", DiagnosticSeverity.Error, "`endwhile` 没有对应的 `while`。"),
            new DiagnosticDescriptor("PEVT2104", "EndWhileHasArguments", DiagnosticSeverity.Error, "`endwhile` 后出现参数。"),

            new DiagnosticDescriptor("PEVT2201", "EndHasArguments", DiagnosticSeverity.Error, "`end` 后出现参数。"),

            new DiagnosticDescriptor("PEVT2301", "EmptyIfBody", DiagnosticSeverity.Warning, "`if` 内没有事件语句。"),
            new DiagnosticDescriptor("PEVT2302", "EmptyElifBody", DiagnosticSeverity.Warning, "`elif` 内没有事件语句。"),
            new DiagnosticDescriptor("PEVT2303", "EmptyElseBody", DiagnosticSeverity.Warning, "`else` 内没有事件语句。"),
            new DiagnosticDescriptor("PEVT2304", "EmptyWhileBody", DiagnosticSeverity.Warning, "`while` 内没有事件语句。"),

            new DiagnosticDescriptor("PEVT2401", "MissingSwitchExpression", DiagnosticSeverity.Error, "`switch` 后没有表达式。"),
            new DiagnosticDescriptor("PEVT2402", "MissingEndSwitch", DiagnosticSeverity.Error, "`switch` 没有对应的 `endswitch`。"),
            new DiagnosticDescriptor("PEVT2403", "EmptySwitch", DiagnosticSeverity.Error, "`switch` 中没有 `case` 或 `default`。"),
            new DiagnosticDescriptor("PEVT2404", "SwitchMustStartWithArm", DiagnosticSeverity.Error, "`switch` 后的第一条语句不是 `case` 或 `default`。"),
            new DiagnosticDescriptor("PEVT2405", "OrphanCase", DiagnosticSeverity.Error, "`case` 不属于任何尚未闭合的 `switch`。"),
            new DiagnosticDescriptor("PEVT2406", "MissingCaseExpression", DiagnosticSeverity.Error, "`case` 后没有表达式。"),
            new DiagnosticDescriptor("PEVT2407", "DuplicateCaseExpression", DiagnosticSeverity.Error, "同一个 `switch` 中存在完全相同的 `case` 表达式。"),
            new DiagnosticDescriptor("PEVT2408", "EmptyCaseBody", DiagnosticSeverity.Warning, "`case` 内没有事件语句。"),
            new DiagnosticDescriptor("PEVT2409", "OrphanDefault", DiagnosticSeverity.Error, "`default` 不属于任何尚未闭合的 `switch`。"),
            new DiagnosticDescriptor("PEVT2410", "DuplicateDefault", DiagnosticSeverity.Error, "同一个 `switch` 中出现多个 `default`。"),
            new DiagnosticDescriptor("PEVT2411", "DefaultHasExpression", DiagnosticSeverity.Error, "`default` 后出现表达式或其他参数。"),
            new DiagnosticDescriptor("PEVT2412", "EmptyDefaultBody", DiagnosticSeverity.Warning, "`default` 内没有事件语句。"),
            new DiagnosticDescriptor("PEVT2413", "OrphanEndSwitch", DiagnosticSeverity.Error, "`endswitch` 没有对应的 `switch`。"),
            new DiagnosticDescriptor("PEVT2414", "EndSwitchHasArguments", DiagnosticSeverity.Error, "`endswitch` 后出现参数。"),
            new DiagnosticDescriptor("PEVT2415", "SideEffectingCaseExpression", DiagnosticSeverity.Error, "`case` 表达式包含 `@`、`_`、`$raw cs`、`await` 或 `status` 等不允许的有副作用或运行时操作。"),

            new DiagnosticDescriptor("PEVT3001", "MissingLabelName", DiagnosticSeverity.Error, "`#` 后没有标签标识符。"),
            new DiagnosticDescriptor("PEVT3002", "InvalidLabelName", DiagnosticSeverity.Error, "`#` 后的内容不是合法标识符。"),
            new DiagnosticDescriptor("PEVT3003", "DuplicateLabel", DiagnosticSeverity.Error, "同一事件重复声明相同标签。"),

            new DiagnosticDescriptor("PEVT3101", "MissingGotoTarget", DiagnosticSeverity.Error, "`goto` 后没有跳转目标。"),
            new DiagnosticDescriptor("PEVT3102", "GotoTargetMustBeLabel", DiagnosticSeverity.Error, "`goto` 的目标没有使用 `#LabelName` 形式。"),
            new DiagnosticDescriptor("PEVT3103", "InvalidGotoTarget", DiagnosticSeverity.Error, "`goto #` 后的内容不是合法标识符。"),
            new DiagnosticDescriptor("PEVT3104", "UndefinedLabel", DiagnosticSeverity.Error, "`goto` 引用的标签未在当前事件中声明。"),
            new DiagnosticDescriptor("PEVT3105", "UnexpectedGotoArgument", DiagnosticSeverity.Error, "标签引用后还有额外参数。"),
            new DiagnosticDescriptor("PEVT3106", "GotoAcrossEventEnvironment", DiagnosticSeverity.Error, "`goto` 的来源与目标分别位于文件外层事件和自定义事件块，或位于不同自定义事件块。"),
            new DiagnosticDescriptor("PEVT3107", "GotoIntoStructuredFlow", DiagnosticSeverity.Error, "目标标签的结构路径不是 `goto` 来源结构路径的前缀；跳转试图进入更深结构、兄弟分支或其他不属于来源路径的结构。"),
            new DiagnosticDescriptor("PEVT3111", "CaseGotoOutsideSwitch", DiagnosticSeverity.Error, "`goto 表达式` 出现在 `switch` 之外。"),
            new DiagnosticDescriptor("PEVT3112", "UndefinedCaseTarget", DiagnosticSeverity.Error, "`goto 表达式` 没有匹配当前 `switch` 中表达式完全相同的 `case`。"),

            new DiagnosticDescriptor("PEVT4001", "EventPathWithoutEnd", DiagnosticSeverity.Error, "存在可达的事件退出路径没有以 `end` 终止。"),
            new DiagnosticDescriptor("PEVT4002", "UnreachableStatement", DiagnosticSeverity.Warning, "事件语句位于同一路径的 `end` 或无条件 `goto` 之后，且没有其他路径可以到达。"),

            new DiagnosticDescriptor("PEVT5001", "InvalidExpression", DiagnosticSeverity.Error, "token 序列不能组成合法表达式。"),
            new DiagnosticDescriptor("PEVT5002", "MissingLeftOperand", DiagnosticSeverity.Error, "除语法位置允许的一元负号外，二元运算符左侧没有表达式。"),
            new DiagnosticDescriptor("PEVT5003", "MissingRightOperand", DiagnosticSeverity.Error, "运算符右侧没有表达式。"),
            new DiagnosticDescriptor("PEVT5004", "ExpressionTypeMismatch", DiagnosticSeverity.Error, "二元运算符左右两侧的表达式类型不同。"),
            new DiagnosticDescriptor("PEVT5005", "OperatorNotDefinedForType", DiagnosticSeverity.Error, "运算符不能用于当前操作数类型。"),
            new DiagnosticDescriptor("PEVT5006", "AssignmentTargetMustBeVariable", DiagnosticSeverity.Error, "`=` 左侧不是已定义且可写的变量。"),
            new DiagnosticDescriptor("PEVT5007", "LogicalOperandMustBeBool", DiagnosticSeverity.Error, "`&`、`|`、`^` 或 `!` 的操作数不是 `bool`。"),
            new DiagnosticDescriptor("PEVT5008", "ConditionMustBeBool", DiagnosticSeverity.Error, "`if`、`elif` 或 `while` 的条件表达式结果不是 `bool`。"),
            new DiagnosticDescriptor("PEVT5009", "SwitchCaseTypeMismatch", DiagnosticSeverity.Error, "`switch` 表达式与某个 `case` 表达式的类型不同。"),
            new DiagnosticDescriptor("PEVT5010", "UnknownType", DiagnosticSeverity.Error, "使用了 `int`、`float`、`bool`、`char`、`string` 以外的类型。"),
            new DiagnosticDescriptor("PEVT5011", "OrderedComparisonRequiresNumber", DiagnosticSeverity.Error, "`<`、`<=`、`>=` 或 `>` 的操作数不是 `int` 或 `float`。"),
            new DiagnosticDescriptor("PEVT5012", "InvalidConversion", DiagnosticSeverity.Error, "使用了 `int → float`、`char → string` 以外的类型转换。"),
            new DiagnosticDescriptor("PEVT5013", "ConversionTargetMustBeVariable", DiagnosticSeverity.Error, "转换标记后不是一个已定义变量。"),
            new DiagnosticDescriptor("PEVT5014", "ConversionMustBeAdjacent", DiagnosticSeverity.Error, "转换标记与变量名之间存在空格或其他 token。"),
            new DiagnosticDescriptor("PEVT5015", "UnterminatedGroupedExpression", DiagnosticSeverity.Error, "左括号 `(` 没有对应的右括号 `)`。"),
            new DiagnosticDescriptor("PEVT5016", "EmptyGroupedExpression", DiagnosticSeverity.Error, "括号内没有表达式。"),
            new DiagnosticDescriptor("PEVT5017", "IntegerLiteralOutOfRange", DiagnosticSeverity.Error, "整数字面量超出标准 32 位有符号整数范围。"),
            new DiagnosticDescriptor("PEVT5018", "FloatLiteralOutOfRange", DiagnosticSeverity.Error, "浮点数字面量超出 IEEE 754 单精度有限值范围。"),
            new DiagnosticDescriptor("PEVT5019", "MalformedNumericLiteral", DiagnosticSeverity.Error, "数值使用了无效的小数点、指数、类型后缀或数字分隔符形式。"),
            new DiagnosticDescriptor("PEVT5020", "InvalidCharacterLiteral", DiagnosticSeverity.Error, "字符字面量解析后不是恰好一个字符。"),
            new DiagnosticDescriptor("PEVT5021", "InvalidLiteralEscape", DiagnosticSeverity.Error, "字符串或字符字面量使用了未定义的转义形式。"),
            new DiagnosticDescriptor("PEVT5022", "AssignmentUsedAsExpression", DiagnosticSeverity.Error, "赋值语句被嵌入初始化器、条件、调用参数、运算表达式或其他赋值语句。"),
            new DiagnosticDescriptor("PEVT5023", "InvalidBooleanLiteral", DiagnosticSeverity.Error, "使用了 `true`、`false` 以外的大小写或数值形式表示布尔字面量。"),
            new DiagnosticDescriptor("PEVT5024", "NumericNegationRequiresNumber", DiagnosticSeverity.Error, "一元负号 `-` 的操作数结果类型不是 `int` 或 `float`。"),

            new DiagnosticDescriptor("PEVT6001", "UndefinedVariable", DiagnosticSeverity.Error, "当前环境中不存在位于使用位置之前、且在所有可达路径上均已执行的变量或常量声明。"),
            new DiagnosticDescriptor("PEVT6002", "ReadOnlyVariableAssignment", DiagnosticSeverity.Error, "赋值目标变量不可写。"),
            new DiagnosticDescriptor("PEVT6003", "UninitializedVariable", DiagnosticSeverity.Error, "普通变量被读取时，存在到达当前位置但尚未完成赋值的可达路径；异步异常产生的未赋值结果由 PolarisEvent 在运行时处理。"),
            new DiagnosticDescriptor("PEVT6004", "MissingDeclarationName", DiagnosticSeverity.Error, "`var` 或 `const` 后没有变量名或常量名。"),
            new DiagnosticDescriptor("PEVT6005", "MissingTypeAnnotation", DiagnosticSeverity.Error, "变量或常量声明没有使用 `:` 显式指定后置类型。"),
            new DiagnosticDescriptor("PEVT6006", "InvalidTypePosition", DiagnosticSeverity.Error, "类型写在变量名或常量名前，或没有位于 `:` 之后。"),
            new DiagnosticDescriptor("PEVT6007", "DuplicateDeclaration", DiagnosticSeverity.Error, "当前变量环境中重复声明相同名称的变量或常量。"),
            new DiagnosticDescriptor("PEVT6008", "InitializerTypeMismatch", DiagnosticSeverity.Error, "初始化表达式类型与显式声明类型不同。"),
            new DiagnosticDescriptor("PEVT6009", "MissingConstInitializer", DiagnosticSeverity.Error, "`const` 声明没有在同一语句中使用 `=` 初始化。"),
            new DiagnosticDescriptor("PEVT6010", "ConstantAssignment", DiagnosticSeverity.Error, "对已经初始化的 `const` 再次赋值。"),
            new DiagnosticDescriptor("PEVT6011", "MissingInitializerExpression", DiagnosticSeverity.Error, "声明中的 `=` 后没有初始化表达式。"),
            new DiagnosticDescriptor("PEVT6012", "VariableOutsideCurrentEnvironment", DiagnosticSeverity.Error, "引用了其他自定义事件块或外层事件环境中的变量、常量或参数。"),
            new DiagnosticDescriptor("PEVT6013", "ReservedKeywordAsIdentifier", DiagnosticSeverity.Error, "保留关键字被用作变量、常量、参数、句柄或集合等待结果变量的名称。"),

            new DiagnosticDescriptor("PEVT7001", "MissingBuiltinName", DiagnosticSeverity.Error, "`@` 后没有内置事件语句名称。"),
            new DiagnosticDescriptor("PEVT7002", "UnknownBuiltinStatement", DiagnosticSeverity.Error, "`@` 后的名称未登记在内置事件语句 API 表中。"),
            new DiagnosticDescriptor("PEVT7003", "InvalidBuiltinCallSyntax", DiagnosticSeverity.Error, "内置事件语句调用不符合 `@名称(参数...)` 语法。"),
            new DiagnosticDescriptor("PEVT7004", "MissingArgumentList", DiagnosticSeverity.Error, "内置事件语句名称后没有 `()` 参数列表。"),
            new DiagnosticDescriptor("PEVT7005", "ArgumentCountMismatch", DiagnosticSeverity.Error, "实参数量与 API 签名中的形参数量不同。"),
            new DiagnosticDescriptor("PEVT7006", "ArgumentTypeMismatch", DiagnosticSeverity.Error, "实参表达式类型与对应形参类型不同。"),
            new DiagnosticDescriptor("PEVT7007", "NoMatchingBuiltinSignature", DiagnosticSeverity.Error, "找不到名称和参数签名完全匹配的内置事件语句 API。"),
            new DiagnosticDescriptor("PEVT7008", "VoidBuiltinUsedAsExpression", DiagnosticSeverity.Error, "没有返回值类型的同步纯调用被用于表达式。"),
            new DiagnosticDescriptor("PEVT7009", "BuiltinReturnTypeMismatch", DiagnosticSeverity.Error, "API 返回值类型与接收位置要求的类型不同。"),
            new DiagnosticDescriptor("PEVT7010", "InvalidBuiltinSignature", DiagnosticSeverity.Error, "API 表中的参数或返回值签名不合法。"),

            new DiagnosticDescriptor("PEVT7101", "MissingCustomBlockName", DiagnosticSeverity.Error, "`_` 后没有自定义事件块名称。"),
            new DiagnosticDescriptor("PEVT7102", "InvalidCustomBlockSignature", DiagnosticSeverity.Error, "自定义事件块定义不符合 `[async] block _名称(参数名 : 类型, ...) [: 返回类型]` 语法。"),
            new DiagnosticDescriptor("PEVT7103", "DuplicateCustomBlockDefinition", DiagnosticSeverity.Error, "重复定义同名自定义事件块。"),
            new DiagnosticDescriptor("PEVT7104", "NestedCustomBlockDefinition", DiagnosticSeverity.Error, "在另一个自定义事件块内部定义自定义事件块。"),
            new DiagnosticDescriptor("PEVT7105", "ReturnOutsideCustomBlock", DiagnosticSeverity.Error, "`return` 位于任何自定义事件块之外。"),
            new DiagnosticDescriptor("PEVT7106", "MissingCustomBlockReturnValue", DiagnosticSeverity.Error, "声明了返回值类型的自定义事件块使用了没有返回目标的 `return`。"),
            new DiagnosticDescriptor("PEVT7107", "UnexpectedCustomBlockReturnValue", DiagnosticSeverity.Error, "未声明返回值类型的自定义事件块在 `return` 后提供了返回目标。"),
            new DiagnosticDescriptor("PEVT7108", "InvalidCustomBlockReturnTarget", DiagnosticSeverity.Error, "`return` 后不是一个已定义变量或常量的名称。"),
            new DiagnosticDescriptor("PEVT7109", "CustomBlockReturnTypeMismatch", DiagnosticSeverity.Error, "`return` 目标的类型与自定义事件块声明的返回值类型不同。"),
            new DiagnosticDescriptor("PEVT7110", "UnknownCustomBlock", DiagnosticSeverity.Error, "调用了尚未定义的自定义事件块。"),
            new DiagnosticDescriptor("PEVT7111", "MissingCustomBlockPrefix", DiagnosticSeverity.Error, "调用已知自定义事件块时省略了名称开头的 `_`。"),
            new DiagnosticDescriptor("PEVT7112", "CustomBlockArgumentCountMismatch", DiagnosticSeverity.Error, "调用实参数量与自定义事件块定义的形参数量不同。"),
            new DiagnosticDescriptor("PEVT7113", "CustomBlockArgumentTypeMismatch", DiagnosticSeverity.Error, "调用实参类型与对应形参类型不同。"),
            new DiagnosticDescriptor("PEVT7114", "VoidCustomBlockUsedAsExpression", DiagnosticSeverity.Error, "无返回值的同步自定义事件块被用于表达式。"),
            new DiagnosticDescriptor("PEVT7115", "CustomBlockUsedBeforeDefinition", DiagnosticSeverity.Error, "在自定义事件块完成定义之前调用该事件块。"),
            new DiagnosticDescriptor("PEVT7116", "MissingCustomBlockEnd", DiagnosticSeverity.Error, "自定义事件块没有使用 `endblock` 显式闭合。"),
            new DiagnosticDescriptor("PEVT7117", "CustomBlockNotAllPathsReturn", DiagnosticSeverity.Error, "声明了返回值类型的自定义事件块存在没有执行有返回值 `return` 就到达 `endblock` 的可达路径。"),
            new DiagnosticDescriptor("PEVT7118", "UnexpectedCustomBlockEnd", DiagnosticSeverity.Error, "`endblock` 位于任何自定义事件块之外，或被用于闭合其他流程语句。"),
            new DiagnosticDescriptor("PEVT7119", "MissingCustomBlockKeyword", DiagnosticSeverity.Error, "看似自定义事件块定义的签名前缺少 `block` 关键字。"),
            new DiagnosticDescriptor("PEVT7120", "EndInsideCustomBlock", DiagnosticSeverity.Error, "自定义事件块内部使用了只允许终止文件外层事件的 `end`。"),

            new DiagnosticDescriptor("PEVT7201", "InvalidAsyncTarget", DiagnosticSeverity.Error, "`async` 被用于 `@` 内置事件语句定义和 `block _` 自定义事件块定义以外的位置。"),
            new DiagnosticDescriptor("PEVT7202", "MissingAsyncSeparator", DiagnosticSeverity.Error, "`async` 与后面的 `@` 或 `block` 之间没有空白字符。"),
            new DiagnosticDescriptor("PEVT7203", "AsyncCallUsedAsOrdinaryValue", DiagnosticSeverity.Error, "异步调用产生的句柄被直接赋给普通变量、常量，或参与普通表达式。"),
            new DiagnosticDescriptor("PEVT7204", "SynchronousCallAssignedToHandler", DiagnosticSeverity.Error, "`handler` 声明的初始化器是静态已知为同步的 `@` 或 `_` 调用；`callevt` 的目标属性改由运行时检查。"),
            new DiagnosticDescriptor("PEVT7205", "MissingHandlerName", DiagnosticSeverity.Error, "`handler` 后没有句柄名称。"),
            new DiagnosticDescriptor("PEVT7206", "MissingHandlerInitializer", DiagnosticSeverity.Error, "`handler` 声明没有使用 `=` 和异步调用立即初始化。"),
            new DiagnosticDescriptor("PEVT7207", "DuplicateHandlerDeclaration", DiagnosticSeverity.Error, "当前环境中句柄名称与已有变量、常量、参数或句柄重名。"),
            new DiagnosticDescriptor("PEVT7208", "HandlerAssignment", DiagnosticSeverity.Error, "尝试对已经初始化的句柄重新赋值。"),
            new DiagnosticDescriptor("PEVT7209", "HandlerUsedAsOrdinaryValue", DiagnosticSeverity.Error, "句柄被用于 `await`、`kill`、`status` 以外的表达式、运算、转换或调用参数。"),
            new DiagnosticDescriptor("PEVT7210", "UndefinedHandler", DiagnosticSeverity.Error, "`await`、`kill` 或 `status` 引用了当前环境中尚未定义的句柄。"),
            new DiagnosticDescriptor("PEVT7211", "AwaitVoidUsedAsExpression", DiagnosticSeverity.Error, "对没有普通返回值的异步操作执行 `await`，并将其作为表达式使用。"),
            new DiagnosticDescriptor("PEVT7212", "InvalidAwaitOperand", DiagnosticSeverity.Error, "`await` 后的名称不是句柄。"),
            new DiagnosticDescriptor("PEVT7213", "InvalidKillOperand", DiagnosticSeverity.Error, "`kill` 后的名称不是句柄。"),
            new DiagnosticDescriptor("PEVT7214", "InvalidStatusOperand", DiagnosticSeverity.Error, "`status` 后的名称不是句柄。"),
            new DiagnosticDescriptor("PEVT7215", "AsyncModifierOnCall", DiagnosticSeverity.Error, "在调用位置写出 `async @...`、`async _...` 或 `async callevt...`；自定义块定义必须写作 `async block _...`，事件使用文件头 `enable async`。"),
            new DiagnosticDescriptor("PEVT7216", "InvalidAggregateAwaitMode", DiagnosticSeverity.Error, "`await` 后使用了 `all`、`any` 以外的集合等待模式。"),
            new DiagnosticDescriptor("PEVT7217", "MissingAggregateAwaitHandlers", DiagnosticSeverity.Error, "`await all` 或 `await any` 没有提供非空句柄列表。"),
            new DiagnosticDescriptor("PEVT7218", "InvalidAggregateAwaitHandler", DiagnosticSeverity.Error, "集合等待的句柄列表包含当前环境中未定义、未初始化或不是句柄的名称。"),
            new DiagnosticDescriptor("PEVT7219", "DuplicateAggregateAwaitHandler", DiagnosticSeverity.Error, "同一个句柄在一次集合等待的输入列表中重复出现。"),
            new DiagnosticDescriptor("PEVT7220", "MissingAggregateAwaitBindings", DiagnosticSeverity.Error, "集合等待的句柄列表后缺少必需的结果绑定括号。"),
            new DiagnosticDescriptor("PEVT7221", "AggregateAwaitBindingCountMismatch", DiagnosticSeverity.Error, "非空结果绑定列表中的变量数量与句柄数量不同。"),
            new DiagnosticDescriptor("PEVT7222", "InvalidAggregateAwaitBinding", DiagnosticSeverity.Error, "结果绑定列表中包含变量名称以外的内容或显式类型声明。"),
            new DiagnosticDescriptor("PEVT7223", "DuplicateAggregateAwaitBinding", DiagnosticSeverity.Error, "结果绑定名称与当前环境中的已有名称或同一绑定列表中的其他名称重复。"),
            new DiagnosticDescriptor("PEVT7224", "AggregateAwaitBindingRequiresReturn", DiagnosticSeverity.Error, "使用了非空结果绑定列表，但至少一个句柄对应的异步定义没有普通返回值，或该句柄来自不产生普通返回值的 `callevt`。"),
            new DiagnosticDescriptor("PEVT7225", "AggregateAwaitBindingInNestedExpression", DiagnosticSeverity.Error, "带非空结果绑定列表的集合等待被嵌入运算、括号、调用参数或其他更大的表达式中。"),

            new DiagnosticDescriptor("PEVT7301", "MissingEventCallTarget", DiagnosticSeverity.Error, "`callevt` 后没有事件 ID 字面量。"),
            new DiagnosticDescriptor("PEVT7302", "InvalidEventCallTarget", DiagnosticSeverity.Error, "`callevt` 的目标不是符合事件 ID 字符规则的非空双引号字面量。"),
            new DiagnosticDescriptor("PEVT7303", "DynamicEventCallTarget", DiagnosticSeverity.Error, "`callevt` 使用变量、表达式或其他动态值作为目标事件 ID。"),
            new DiagnosticDescriptor("PEVT7304", "EventCallUsedAsExpression", DiagnosticSeverity.Error, "`callevt` 被用于普通变量、常量、运算、调用参数或其他普通表达式位置。"),
            new DiagnosticDescriptor("PEVT7305", "AsyncModifierOnEventCall", DiagnosticSeverity.Error, "调用位置写出 `async callevt`；事件是否异步只能由目标文件的 `enable async` 标记决定。"),

            new DiagnosticDescriptor("PEVT7401", "MissingExecArgument", DiagnosticSeverity.Error, "`exec()` 没有提供参数。"),
            new DiagnosticDescriptor("PEVT7402", "ExecArgumentCountMismatch", DiagnosticSeverity.Error, "`exec(...)` 的参数数量不是一个。"),
            new DiagnosticDescriptor("PEVT7403", "ExecArgumentMustBeString", DiagnosticSeverity.Error, "`exec` 参数表达式的静态结果类型不是 `string`。"),
            new DiagnosticDescriptor("PEVT7404", "ExecUsedAsExpression", DiagnosticSeverity.Error, "`exec(...)` 被用于初始化器、赋值右侧、运算、调用参数或其他表达式位置。"),
            new DiagnosticDescriptor("PEVT7405", "AsyncModifierOnExec", DiagnosticSeverity.Error, "使用 `async exec(...)`；动态片段执行语句本身不能声明为异步。"),
            new DiagnosticDescriptor("PEVT7406", "ExecUsedAsHandlerInitializer", DiagnosticSeverity.Error, "使用 `handler 名称 = exec(...)`；`exec` 不产生异步句柄。"),

            new DiagnosticDescriptor("PEVT8001", "MissingRawTarget", DiagnosticSeverity.Error, "`$raw` 后没有调用目标。"),
            new DiagnosticDescriptor("PEVT8002", "InvalidRawTarget", DiagnosticSeverity.Error, "`$raw` 后的调用目标不是 `cmd` 或 `cs`。"),
            new DiagnosticDescriptor("PEVT8003", "MissingRawBlock", DiagnosticSeverity.Error, "`$raw cmd` 或 `$raw cs` 后没有原始文本块。"),
            new DiagnosticDescriptor("PEVT8004", "UnterminatedRawBlock", DiagnosticSeverity.Error, "原始文本块没有以三个 ASCII 单引号 `'''` 闭合。"),
            new DiagnosticDescriptor("PEVT8005", "UnexpectedRawArgument", DiagnosticSeverity.Error, "原始文本块结束后还有额外参数或 token。"),
            new DiagnosticDescriptor("PEVT8006", "RawCallUsedAsExpression", DiagnosticSeverity.Error, "`$raw cmd` 被用于表达式，或无返回值的 `$raw cs` 被用于表达式。"),
            new DiagnosticDescriptor("PEVT8007", "InvalidRawCSharp", DiagnosticSeverity.Error, "`$raw cs` 中的内容不是合法的 C# 语句。"),
            new DiagnosticDescriptor("PEVT8008", "InvalidRawCSharpReturnType", DiagnosticSeverity.Error, "`$raw cs` 返回了 `int`、`float`、`bool`、`char`、`string` 以外的类型。"),
            new DiagnosticDescriptor("PEVT8009", "InconsistentRawCSharpReturnType", DiagnosticSeverity.Error, "同一个 `$raw cs` 代码块中的有值 `return` 返回了不同的 PEVT 类型。"),
            new DiagnosticDescriptor("PEVT8010", "RawCSharpNotAllPathsReturn", DiagnosticSeverity.Error, "`$raw cs` 作为表达式使用，但存在可达的 C# 退出路径没有返回值。"),
            new DiagnosticDescriptor("PEVT8011", "InvalidRawCSharpArgumentList", DiagnosticSeverity.Error, "`$raw cs` 的变量传入列表不符合 `(变量名, ...)` 语法。"),
            new DiagnosticDescriptor("PEVT8012", "RawCSharpArgumentMustBeVariable", DiagnosticSeverity.Error, "`$raw cs` 的变量传入列表中包含了表达式或其他非变量内容。"),
            new DiagnosticDescriptor("PEVT8013", "DuplicateRawCSharpArgument", DiagnosticSeverity.Error, "同一个变量在一个 `$raw cs` 变量传入列表中重复出现。"),
            new DiagnosticDescriptor("PEVT8014", "UndefinedRawCSharpArgument", DiagnosticSeverity.Error, "`$raw cs` 的变量传入列表引用了尚未定义的 PEVT 变量。"),
            new DiagnosticDescriptor("PEVT8015", "RawCSharpNotEnabled", DiagnosticSeverity.Error, "当前文件使用了 `$raw cs`，但没有在 `id` 后紧接着声明 `enable cs`。"),
            new DiagnosticDescriptor("PEVT8016", "RawBlockMustBeAdjacent", DiagnosticSeverity.Error, "原始文本块开始分隔符 `'''` 没有紧贴左侧的 `cmd`、`cs` 或 C# 变量传入列表右括号 `)`。"),
            new DiagnosticDescriptor("PEVT8017", "InvalidRawDelimiterEscape", DiagnosticSeverity.Error, "原始内容试图转义结束分隔符，但没有使用规定的 `\\'''` 形式。"),

            new DiagnosticDescriptor("PEVT9001", "InternalStaticAnalysisError", DiagnosticSeverity.Error, "PEVT 加载、解析或静态分析发生内部异常，且错误不由合法的源语法诊断覆盖。"),
        };

        public static IReadOnlyList<DiagnosticDescriptor> All { get; } = Array.AsReadOnly(Entries);

        private static readonly IReadOnlyDictionary<string, DiagnosticDescriptor> ById =
            Entries.ToDictionary(entry => entry.Id);

        public static DiagnosticDescriptor Find(string id) => ById.TryGetValue(id ?? string.Empty, out var d) ? d : null;

        public static bool TryFind(string id, out DiagnosticDescriptor descriptor) =>
            ById.TryGetValue(id ?? string.Empty, out descriptor);
    }
}
